#FOR AND WHILE TASK:

#TASK 1 Counting between values

# number_one = int(input('Enter first value from range 1 to 100: '))
# number_two = int(input('Enter second value from range 1 to 100: '))

# if number_one > number_two and number_one >0 and number_one < 101 and number_two > 0 and number_two < 101:
#     while number_two <= number_one:
#         print(f'Counting: {number_two}')
#         number_two +=1
# elif number_one < number_two and number_one >0 and number_one < 101 and number_two > 0 and number_two < 101:
#       while number_one <= number_two:
#         print(f'Counting: {number_one}')
#         number_one +=1
# elif number_one == number_two:
#     print('You enter equal numbers')
# else:
#     print('Error wrong value')
    
#TASK 2 print word in reverse order

# word = input('Enter the word: ')
# new_word = ""
# counter = 0
# for char in word:
#     new_word = char + new_word
        
# print(f'This word in reverse order is {new_word}')

#TASK 3 print times table for given value between 1 to 12

# number = input('Enter the number in range from 1 to 12: ')

# while (not number.isdigit()) or int(number) < 1 or int(number) > 12:
#     print("Wrong type of enter")
#     number = input('Enter the number in range from 1 to 12: ')
    
# for digit in range(1,11):
#     print(f'{digit} x {number} = {digit*int(number)}')

#TASK 4 use for loop to print times table for values 1 to 12

# for i in range(1,11):
#     print(f'This is {i} times table:')
    
#     for n in range(1,11):
#         print(f'{i} x {n} = {i*n}')
        
#     print("="*15)

#TASK 5 ask user to insert value and calculate the mean

# print("This program calculate mean, if you wanna finish enter:exit")

# input_temp = ''
# input_sum = 0
# devider = 0
# while input_temp != 'exit' :
#     input_temp = input("Enter the value: ")
#     if input_temp.isdigit():
#         input_sum += int(input_temp)
#         devider +=1
#     else:
#         print("Please enter int value or exit to finish")
        
# print(f'The mean  = {input_sum} / {devider} = {input_sum/devider}')

#TASK 6 write program with calculate factoral of input value

# result_of_factoral = input("Enter the value of factoral:")

# while not result_of_factoral.isdigit():
#     result_of_factoral = input("Enter the correct value of factoral:")

# result_of_factoral = int(result_of_factoral)

# for i in range(1,result_of_factoral):
#     result_of_factoral = result_of_factoral * i

# print(f'The factoral of value 15 is: {result_of_factoral}')

#TASK 7 write program with calculate input values of Fibonacci numbers in list

# numbers_of_values = input("Enter how many Fibonnaci numbers do you need:")
# Fibonnaci_list=[]

# while not numbers_of_values.isdigit():
#     numbers_of_values = input("Enter the correct value: ")

# numbers_of_values = int(numbers_of_values)

# for i in range(numbers_of_values):
#     print(i,end=" ")
#     if i == 0:
#         Fibonnaci_list.append(0)
#     elif i == 1:
#         Fibonnaci_list.append(1)
#     else:
#         Fibonnaci_list.append((Fibonnaci_list[i-2] + Fibonnaci_list[i-1]))

# print(f'The Fibonnaci list : {Fibonnaci_list}')

#TASK 8 print strange combination of stars

# print("Generated by print function")
# print("\t*****\n\t*\n\t****\n\t*\n\t*\n\t*")
# print('\nGenerated by for loop with if:')


# for i in range(6):
#     for j in range(13):
#         if j < 8:
#             print(" ",end="")
#         elif i == 0 and j < 13:
#             print("*",end="")
#         elif i == 1 and j < 9:
#             print("*",end="")
#         elif i == 2 and j < 12:
#             print("*",end="")
#         elif i == 3 and j < 9:
#             print("*",end="")
#         elif i == 4 and j < 9:
#             print("*",end="")
#         elif i == 5 and j < 9:
#             print("*",end="")
            
#     print()

#TAKS 9 Print evens and odds values form 1 to 100 in list

# evens_list=[]
# odds_list=[]

# for i in range(1,101):
#     if i % 2 == 0:
#         evens_list.append(i)
#     else:
#         odds_list.append(i)

# print(f'The list of evens: {evens_list}\n')
# print(f'The list of odds: {odds_list}\n')